namespace SwiftlyS2.Shared.Misc;

public enum GamePhase : short
{
  GAMEPHASE_WARMUP_ROUND = 0,
  GAMEPHASE_PLAYING_STANDARD = 1,
  GAMEPHASE_PLAYING_FIRST_HALF = 2,
  GAMEPHASE_PLAYING_SECOND_HALF = 3,
  GAMEPHASE_HALFTIME = 4,
  GAMEPHASE_MATCH_ENDED = 5,
  GAMEPHASE_MAX = 6
}